### ISSUE TITLE
Request ability to input MQTT Broker credentials within add-on config

### ISSUE THREAD

**Issue by HeliFlyer73** [smarthall/hassio-addons#2]
As per the issue encountered in the HA community thread:

https://community.home-assistant.io/t/ecowitt2mqtt-send-data-from-an-ecowitt-device-to-mqtt/231169/38

It would be great to be able to input MQTT Broker credentials within the config addon of Ecowitt2Mqtt.

**Comment by smarthall** [comment]
This seems easy enough to do, but I'm interested in your use case. Is this because you have a MQTT server that is separate to your hassio node? Would it make sense that if the MQTT server was set in the configuration it would override the automatically discovered one?

**Comment by HeliFlyer73** [comment]
Yes, correct -the MQTT Broker runs in a docker on the NAS. The HA is in the same NAS but on a VM. yes, I believe the Config set would override the auto. - Potentially making this easier to configure, if one does not have AutoDiscover enabled as well?
Thanks.

**Comment by HeliFlyer73** [comment]
Yes, correct -the MQTT Broker runs in a docker on the NAS. The HA is in the same NAS but on a VM. yes, I believe the Config set would override the auto. - Potentially making this easier to configure, if one does not have AutoDiscover enabled as well?
Thanks.

[EDIT] - I see you are in Melbourne! - Hey, me too!

**Comment by smarthall** [comment]
Okay I've pushed version `1.0.10-11`, you should be able to update shortly. Test it and let me know.

Hi from the northern suburbs!

**Comment by HeliFlyer73** [comment]
Hi Daniel,

Success. worked a treat, all the sensors have been discovered. 

Thanks for the addition

Regards,

Jarrod.  In the North East!

**Comment by smarthall** [comment]
Glad I could help!
