### ISSUE TITLE
HA Addon will not install.

### ISSUE THREAD

**Issue by jbrukardt** [smarthall/hassio-addons#3]
Upon attempting to install the integration from the custom repository in Home Assistant, nothing happens.  The circle spins for a bit and then stops and the integration does not install.

**Comment by smarthall** [comment]
Hey, sorry this has taken me a while to get to. I've been on holiday.

This extension is built by your HA machine itself so it can take a while to download and run the required components. This means it often takes longer than other addons to install.

I'll be looking into building actual docker images for it sometime soon.

**Comment by lucamargoni** [comment]
Hey, same issue . The error message is: 

"Impossibile installare il componente aggiuntivo
The command '/bin/ash -o pipefail -c apk add --no-cache python3 && apk add --no-cache --virtual .build-dependencies gcc python3-dev libc-dev musl-dev && python3 -m ensurepip && pip3 install --no-cache --upgrade pip setuptools && pip install ecowitt2mqtt==1.0.10 && apk del .build-dependencies' returned a non-zero code: 127_"

thanks!

**Comment by jbrukardt** [comment]
> Hey, sorry this has taken me a while to get to. I've been on holiday.
> 
> This extension is built by your HA machine itself so it can take a while to download and run the required components. This means it often takes longer than other addons to install.
> 
> I'll be looking into building actual docker images for it sometime soon.

Upon clicking install, the circle (over the install button) spins for 22 seconds then vanishes.   I let it sit on the install page for another 10 minutes and it never changed.   

I think it may be something else.   ill check logs to see if im getting the same error as @lucamargoni

**Comment by jbrukardt** [comment]
Different issue it appears

```
Step 4/12 : RUN apk add --no-cache         python3     && apk add --no-cache --virtual .build-dependencies         gcc         python3-dev         libc-dev         musl-dev     && python3 -m ensurepip     && pip3 install --no-cache --upgrade pip setuptools     && pip install ecowitt2mqtt==1.0.10     && apk del .build-dependencies
 ---> Running in 0e447a335fd6
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/6) Installing libbz2 (1.0.8-r1)
(2/6) Installing expat (2.2.10-r1)
(3/6) Installing libffi (3.3-r2)
(4/6) Installing gdbm (1.19-r0)
(5/6) Installing sqlite-libs (3.34.1-r0)
(6/6) Installing python3 (3.8.10-r0)
Executing busybox-1.32.1-r6.trigger
OK: 74 MiB in 49 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/14) Installing binutils (2.35.2-r1)
(2/14) Installing libgomp (10.2.1_pre1-r3)
(3/14) Installing libatomic (10.2.1_pre1-r3)
(4/14) Installing libgphobos (10.2.1_pre1-r3)
(5/14) Installing gmp (6.2.1-r0)
(6/14) Installing isl22 (0.22-r0)
(7/14) Installing mpfr4 (4.1.0-r0)
(8/14) Installing mpc1 (1.2.0-r0)
(9/14) Installing gcc (10.2.1_pre1-r3)
(10/14) Installing pkgconf (1.7.3-r0)
(11/14) Installing python3-dev (3.8.10-r0)
(12/14) Installing musl-dev (1.2.2-r0)
(13/14) Installing libc-dev (0.7.2-r3)
(14/14) Installing .build-dependencies (20210520.154042)
Executing busybox-1.32.1-r6.trigger
OK: 232 MiB in 63 packages
Looking in links: /tmp/tmp9_pnne0j
Processing /tmp/tmp9_pnne0j/setuptools-56.0.0-py3-none-any.whl
Processing /tmp/tmp9_pnne0j/pip-21.1.1-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-21.1.1 setuptools-56.0.0
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (56.0.0)
Collecting setuptools
  Downloading setuptools-56.2.0-py3-none-any.whl (785 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-56.2.0
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

/bin/ash: pip: not found

Removing intermediate container 0e447a335fd6
```

**Comment by smarthall** [comment]
I'm going to start pre-building the images to fix this issue. I've done the work to [build the containers](https://github.com/smarthall/containers/runs/3300073850?check_suite_focus=true), I just need to publish them to Docker Hub and point the repository there. Expect a fix shortly.

**Comment by smarthall** [comment]
Version `1.3.0-2` now uses a prebuilt image for all architectures. This should prevent this issue from happening again, and should make installs faster (Bonus!).
