### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by edouardkleinhans** [smarthall/hassio-addons#4]
Hello, 

can you update this addon to the latest version of ecowitt ?

**Comment by smarthall** [comment]
Thanks for the reminder, I'll get to it tomorrow some time.

**Comment by smarthall** [comment]
Okay so I'm trying to solve this and #3 at once. I've got the [docker images building](https://github.com/smarthall/containers/runs/3300073850?check_suite_focus=true), I just have to push them to Docker hub and link the repository there. Should be able to do that tomorrow...

**Comment by smarthall** [comment]
Done, version `1.3.0-2` of the addon includes the latest version of ecowitt2mqtt (`v1.3.0`)

**Comment by MagicMountainMan** [comment]
FYI updating to the latest version completely broke my setup giving me an error and I had to reinstall it.

**Comment by smarthall** [comment]
Yeah I think there may be a bug in home assistant when moving from a 'local build' to a 'prebuilt' addon. I'm trying to chase it down.

What architecture are you running Home Assistant on @MagicMountainMan?

**Comment by MagicMountainMan** [comment]
> What architecture are you running Home Assistant on @MagicMountainMan?

I'm running full fat Home Assistant in a VM on unRAID.

**Comment by RatMondeo** [comment]
Hi, thanks for your work on this.  Mine broke also on upgrade attempt with:
Failed to restart add-on
404 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_3390ca00_ecowitt: Not Found ("No such image: smarthall/aarch64-ecowitt2mqtt:1.3.0-2")

core-2021.8.6
Home Assistant OS 6.2
Pi4

**Comment by smarthall** [comment]
@RatMondeo That's the issue I'm seeing for people migrating. I'm still trying to gather information to report to the HA devs. In the meantime the workaround is to uninstall the addon then reinstall. Let me know how that goes.

**Comment by smarthall** [comment]
I've made an issue for this problem specifically. See #5

**Comment by RatMondeo** [comment]
Thanks for the workaround, uninstalled, and reinstalled new version, and now updated.

Cheers
