### ISSUE TITLE
Question: New versions of ecowitt2mqtt

### ISSUE THREAD

**Issue by VictorvandenHoven** [smarthall/hassio-addons#6]
More of a question in stead of an issue:

Not sure how the updating of addons work in HA, but do you have to change the config.json and Dockerfile by hand each time a new version of the ecowitt2mqtt image  is  available?  
Do you do that that yourself actively, or do you prefer PR's?

I am exciting to try out some changes in the new version 2.0.2  of ecowitt2mqtt  in HomeAssistant, that's why I am asking.

**Comment by smarthall** [comment]
I normally do that myself (though sometimes it takes me a week or so), but I will also accept PRs if you want it faster. ;-)

**Comment by smarthall** [comment]
I should note that I haven't done 2.0.2 because it didn't get an official Github Release, and so i didn't get notified. https://github.com/bachya/ecowitt2mqtt/releases

**Comment by smarthall** [comment]
`2.0.2` is now live.
