### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by w1ll1am23** [smarthall/hassio-addons#8]
set this up today and I'm having issue. I see logs saying the data was send to Home Assistant, but nothing in my MQTT logs. Manually ran ecowitt2mqtt from another system and discovery worked fine. 

There are no required settings for this add-on right? So I'm confused why I'm having issue. 

I did try manually setting the host and port, no difference.

**Comment by smarthall** [comment]
Hi William,

The default config should talk to the MQTT server running in an addon on the same system. Supervisor sends the connection details to this addon via environment variables.

You could try manually specifying the MQTT server details...

**Comment by w1ll1am23** [comment]
I've tried both, I even see the client connect (I think will need to double check that) running ecowitt2mqtt in a docker container on another host is working fine as well

**Comment by smarthall** [comment]
Wow, that is really interesting (and annoying to debug). You could try following [these instructions](https://community.home-assistant.io/t/protip-how-to-get-shell-in-actual-homeassistant-or-addon-container-when-using-hassio/48760/4) to get a shell into the container running ecowitt2mqtt. From these you could check that the environment variables are correct, and potentially debug the process with strace or similar.

**Comment by w1ll1am23** [comment]
I'll try to give that a shot.

**Comment by smarthall** [comment]
Did you ever sort this out?

**Comment by smarthall** [comment]
If you find out more information, or need any help debugging this further, please feel free to reopen this issue.
